export const GET_ALL_TIME_ZONES = 'GET_ALL_TIME_ZONES';
export type GET_ALL_TIME_ZONES = typeof GET_ALL_TIME_ZONES;

export const GET_ALL_TIME_ZONES_FAILED = 'GET_ALL_TIME_ZONES_FAILED';
export type GET_ALL_TIME_ZONES_FAILED = typeof GET_ALL_TIME_ZONES_FAILED;

export const GET_ALL_TIME_ZONES_SUCCESS = 'GET_ALL_TIME_ZONES_SUCCESS';
export type GET_ALL_TIME_ZONES_SUCCESS = typeof GET_ALL_TIME_ZONES_SUCCESS;

export const ADD_TIME_ZONE = 'ADD_TIME_ZONE';
export type ADD_TIME_ZONE = typeof ADD_TIME_ZONE;

export const ADD_TIME_ZONE_FAILED = 'ADD_TIME_ZONE_FAILED';
export type ADD_TIME_ZONE_FAILED = typeof ADD_TIME_ZONE_FAILED;

export const ADD_TIME_ZONE_SUCCESS = 'ADD_TIME_ZONE_SUCCESS';
export type ADD_TIME_ZONE_SUCCESS = typeof ADD_TIME_ZONE_SUCCESS;

export const EDIT_TIME_ZONE = 'EDIT_TIME_ZONE';
export type EDIT_TIME_ZONE = typeof EDIT_TIME_ZONE;

export const EDIT_TIME_ZONE_FAILED = 'EDIT_TIME_ZONE_FAILED';
export type EDIT_TIME_ZONE_FAILED = typeof EDIT_TIME_ZONE_FAILED;

export const EDIT_TIME_ZONE_SUCCESS = 'EDIT_TIME_ZONE_SUCCESS';
export type EDIT_TIME_ZONE_SUCCESS = typeof EDIT_TIME_ZONE_SUCCESS;

export const DELETE_TIME_ZONE = 'DELETE_TIME_ZONE';
export type DELETE_TIME_ZONE = typeof DELETE_TIME_ZONE;

export const DELETE_TIME_ZONE_FAILED = 'DELETE_TIME_ZONE_FAILED';
export type DELETE_TIME_ZONE_FAILED = typeof DELETE_TIME_ZONE_FAILED;

export const DELETE_TIME_ZONE_SUCCESS = 'DELETE_TIME_ZONE_SUCCESS';
export type DELETE_TIME_ZONE_SUCCESS = typeof DELETE_TIME_ZONE_SUCCESS;
