export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export type AUTHENTICATE_USER = typeof AUTHENTICATE_USER;

export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export type AUTHENTICATE_USER_FAILED = typeof AUTHENTICATE_USER_FAILED;

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export type AUTHENTICATE_USER_SUCCESS = typeof AUTHENTICATE_USER_SUCCESS;

export const REGISTER_USER = 'REGISTER_USER';
export type REGISTER_USER = typeof REGISTER_USER;

export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export type REGISTER_USER_FAILED = typeof REGISTER_USER_FAILED;

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export type REGISTER_USER_SUCCESS = typeof REGISTER_USER_SUCCESS;

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export type GET_CURRENT_USER = typeof GET_CURRENT_USER;

export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
export type GET_CURRENT_USER_FAILED = typeof GET_CURRENT_USER_FAILED;

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export type GET_CURRENT_USER_SUCCESS = typeof GET_CURRENT_USER_SUCCESS;
