export const GET_ALL_USERS = 'GET_ALL_USERS';
export type GET_ALL_USERS = typeof GET_ALL_USERS;

export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export type GET_ALL_USERS_FAILED = typeof GET_ALL_USERS_FAILED;

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export type GET_ALL_USERS_SUCCESS = typeof GET_ALL_USERS_SUCCESS;

export const ADD_USER = 'ADD_USER';
export type ADD_USER = typeof ADD_USER;

export const ADD_USER_FAILED = 'ADD_USER_FAILED';
export type ADD_USER_FAILED = typeof ADD_USER_FAILED;

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export type ADD_USER_SUCCESS = typeof ADD_USER_SUCCESS;

export const EDIT_USER = 'EDIT_USER';
export type EDIT_USER = typeof EDIT_USER;

export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export type EDIT_USER_FAILED = typeof EDIT_USER_FAILED;

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export type EDIT_USER_SUCCESS = typeof EDIT_USER_SUCCESS;

export const DELETE_USER = 'DELETE_USER';
export type DELETE_USER = typeof DELETE_USER;

export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export type DELETE_USER_FAILED = typeof DELETE_USER_FAILED;

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export type DELETE_USER_SUCCESS = typeof DELETE_USER_SUCCESS;
